# Generated by Django 4.2.2 on 2023-06-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.TextField(default='')),
                ('question', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_question',
                'indexes': [models.Index(fields=['email'], name='user_question_email')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_id', models.CharField(max_length=120, unique=True)),
                ('address_line1', models.CharField(max_length=127, null=True)),
                ('address_line2', models.CharField(max_length=127, null=True)),
                ('address_city', models.CharField(max_length=127, null=True)),
                ('address_state', models.CharField(max_length=127, null=True)),
                ('address_country', models.CharField(max_length=127, null=True)),
                ('address_zip', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=254, null=True)),
                ('email', models.CharField(max_length=254, null=True)),
                ('brand', models.CharField(max_length=20)),
                ('exp_month', models.SmallIntegerField(null=True)),
                ('exp_year', models.SmallIntegerField(null=True)),
                ('funding', models.CharField(max_length=20, null=True)),
                ('last4', models.CharField(max_length=4, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_payment_method',
                'indexes': [models.Index(fields=['method_id'], name='payment_method_id'), models.Index(fields=['user_id'], name='payment_method_user_id')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=60, unique=True)),
                ('invoice_path', models.TextField(default=None, null=True)),
                ('subtotal', models.FloatField(default=None, null=True)),
                ('tax', models.FloatField(default=None, null=True)),
                ('total', models.FloatField(default=None, null=True)),
                ('fee', models.FloatField(default=None, null=True)),
                ('net', models.FloatField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_payment_intent_id', models.CharField(max_length=120)),
                ('stripe_invoice_id', models.CharField(max_length=120)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'invoice',
                'indexes': [models.Index(fields=['user_id'], name='invoice_user_id')],
            },
        ),
        migrations.CreateModel(
            name='API_Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=254)),
                ('meta_value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_meta',
                'indexes': [models.Index(fields=['meta_key'], name='api_meta_key')],
            },
        ),
    ]
